// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EFModels.Models
{
    public partial class EcpayOrder
    {
        [Key]
        [StringLength(50)]
        public string MerchantTradeNo { get; set; }
        public int MemberID { get; set; }
        public int? RtnCode { get; set; }
        [StringLength(50)]
        public string RtnMsg { get; set; }
        [StringLength(50)]
        public string TradeNo { get; set; }
        public int? TradeAmt { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? PaymentDate { get; set; }
        [StringLength(50)]
        public string PaymentType { get; set; }
        [StringLength(50)]
        public string PaymentTypeChargeFee { get; set; }
        [StringLength(50)]
        public string TradeDate { get; set; }
        public int? SimulatePaid { get; set; }
        [StringLength(300)]
        public string TradeDesc { get; set; }
        public int? ItemId { get; set; }
        public int? fk_typeId { get; set; }

        [ForeignKey("fk_typeId")]
        [InverseProperty("EcpayOrders")]
        public virtual Type fk_type { get; set; }
    }
}