// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EFModels.Models
{
    public partial class ShoesSize
    {
        public ShoesSize()
        {
            ShoesGroups = new HashSet<ShoesGroup>();
        }

        [Key]
        public int SizeId { get; set; }
        [Required]
        [StringLength(50)]
        public string SizeName { get; set; }

        [InverseProperty("fk_Size")]
        public virtual ICollection<ShoesGroup> ShoesGroups { get; set; }
    }
}